In [23]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 90%; }
    div#menubar-container     { width: 90%; }
    div#maintoolbar-container { width: 99%; }a
</style>
"""))

# 1.  IF condition

<font size = "5"> Features </font>


We are going to cover certain functions necessary to be able to write ours. for
1. We will learn to use the **if** function.
2. We will see the types of **Loops** in Python.
3. Structure of a **function**.
4. Structure of a **class**.
5. We will build a **project** using everything we have learned.

# If condition

Function **if** test conditions. 
- Equals: a == b
- Not Equals: a != b
- Less than: a < b
- Less than or equal to: a <= b
- Greater than: a > b
- Greater than or equal to: a >= b

<img src="../images/if-statement.jpg" alt="image info" />

### The structure of the code is the following: <br><br>

<font size="4">
if <font color='green'>test expresion</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code to excute<br>
</font>

The function **if** tests the veracity of a logic expression. The result of test statement should be a **<font color='red'>boolean</font>**. In other words, the output of the test statemen must be **<font color='red'>True</font>** or **<font color='red'>False</font>**. To sum, any function that its output is **boolean** can be used as a test expression in the **if** function.

In [8]:
A = 20
B = 30

result = A == B
print( f'result A == B \t{result} \n')

result A == B 	False

result A != B 	  True

result A > B 	 False

## Test more than 1 expression

We will use **elif**. This function allows us to add more test expressions.  <br><br>



<font size="4">
if <font color='green'>test expresion1</font>: <br>
&nbsp;&nbsp;&nbsp;&nbsp;Code1<br><br>
elif <font color='green'>test expresion2</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code2<br><br>
elif <font color='green'>test expresion3</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code3<br><br>
elif <font color='green'>test expresion4</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code4<br><br>
elif <font color='green'>test expresion5</font>:<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code5<br><br>
else :<br>
&nbsp;&nbsp;&nbsp;&nbsp;Code6<br><br>
</font>

Python will read the conditions of the test in order. 
If **Test expression 1** is `True`, the rest of the test expressions will not be evaluated. 
R execute **Code2** and will not test the next conditions. <br>

In case no Test expression is `True`, the **Code6** will be excuted.

In [9]:
A = 20
B = 30

if A == B:
    print( 'Test expresion 1 is True' )
    
elif A > B:
    print( 'Test expresion 2 is True' )

elif A >= B:
    print( 'Test expresion 3 is True' )
    
elif A < B:
    print( 'Test expresion 4 is True' )
    
elif A <= B:
    print( 'Test expresion 5 is True' )
    
else:
    
        print( 'Test expresion 6 is True' )

Test expresion 4 is True

# Python Nested if Statement

In [10]:
total = 100
#country = "PE"
country = "AR"
if country == "PE":
    if total <= 50:
        print("Shipping Cost is  $50")
    elif total <= 100:
        print("Shipping Cost is $25")
    elif total <= 150:
        print("Shipping Costs $5")
    else:
        print("FREE")
        
if country == "AR": 
    if total <= 50:
        print("Shipping Cost is  $100")
    else:
        print("FREE")

FREE

# Conclusion

The **if** function is not only useful with logical expressions, but also with functions whose result is a **<font color = 'red' > Boolean </font>** (**True** or **False**).<br>
For example, the **isinstance** function evaluates whether a variable is string, bool, int, float and returns a Boolean (True or False) as a result. For more information [here](https://docs.python.org/3/library/functions.html#isinstance). <br>

In [11]:
A = 20
# A = np.array([3, 4, 5])

if isinstance( A, str ):
    print( 'A is a string' )

elif isinstance( A, bool ):
    print( 'A is a boolean' )

elif isinstance( A, float ):
    print( 'A is a float' )

elif isinstance( A, int ):
    print( 'A is an integer' )

elif isinstance( A, complex ):
    print( 'A is a complex' )

else:
    print( 'A is another type of variable')

A is an integer

# Loops
Estudiaremos los 2 tipos de loops en python. Un loop es una función que permite realizar tareas de manera iterativa cierto número de veces (for loop) o mientras una condición sea verdadera (while loop).

## While Loop
While loop es utilizado para repetir código mientras la condición se mantenga verdadera. Cuando la expresión lógica sea falsa, el código terminará de ejecutarse. [More Info](https://python101.pythonlibrary.org/chapter5_loops.html)
<img src="../images\while_loop.jpg">

In [12]:
i = 1

while i < 6:
    
    print(i)
    
    i += 1   # equivalents i = i +1

1
2
3
4
5

## While nad break

In [14]:
i = 0
while(i < 6):
    print(i)
    if (i == 4):
        break
    else:
        i+=1

0
1
2
3
4

In [15]:
# Utilizaremos el paquete np.
import numpy as np

edad = np.array([ 3, 6, 7, 10, 15, 17, 18, 31, 26, 88 , 100, 120, 110])
i = 0

while i < edad.size:
    
    print(edad[i])
    i += 1

3
6
7
10
15
17
18
31
26
88
100
120
110

### If I have my savings today of S/.1,000.00. How much will my savings be worth in 10 years at an interest rate of 2.5%?

$$
S_{y+1}	=S_{y}(1+i)
$$

In [16]:
#  sasve
S = 1000

# Periods
n = 10

# interes rate
i = 0.025

In [17]:
year = 1
while year < n:
    S +=  S * i
    year += 1
    print( year, S)

2 1025.0
3 1050.625
4 1076.890625
5 1103.812890625
6 1131.408212890625
7 1159.6934182128907
8 1188.685753668213
9 1218.4028975099184
10 1248.8629699476664

In [18]:
import pandas as pd
data1 = {'nombres': ['Marcelo', 'Octavio', 'Fredy', 'Felipe', 'Arturo', 'Anzony', 'Finado', 'Alex', 'Anny', 'Yampi'], 
     'edad': [23, 25, 36, 78, 90, 32, 200, 24, 12, 18]}

personas = pd.DataFrame( data = data1) #a partir de un diccionario se crea un data frame

personas

In [4]:
#quedarse con una columna

personas.edad

personas['edad']

NameError: name 'personas' is not defined

In [3]:
personas[['edad']] #doble corchete para que quede como dataframe

NameError: name 'personas' is not defined

In [ ]:
personas

In [19]:
i = 0

# row by row
nrows = personas.edad.count()
while i < nrows:
  
    if personas['edad'][i] > 100:
        print('Que fue loco fantasmas')
        break
    
    elif personas['edad'][i] < 18:
        # Hemos creado una nueva columna y la estamos rellenando
        personas.loc[[i], ["pasa"]] = "No pasa"
    
    else:
        personas.loc[[i], ["pasa"]] = "Pasa"
        # otra forma
        # personas['pasa'][i] = 'pasa'
    i = i +1

Que fue loco fantasmas

In [20]:
personas

   nombres  edad  pasa
0  Marcelo    23  Pasa
1  Octavio    25  Pasa
2    Fredy    36  Pasa
3   Felipe    78  Pasa
4   Arturo    90  Pasa
5   Anzony    32  Pasa
6   Finado   200   NaN
7     Alex    24   NaN
8     Anny    12   NaN
9    Yampi    18   NaN

# 2. For loops


A for loop is used for iterating over a sequence. It executes a code a definite number of times. It has the following structure:

<img src="../images/for_loop.jpg" alt="image info" />

In [21]:
ages = [ 21, 23, 25, 24, 20]

for age in ages:
    print( type(age) )

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>

In [ ]:
# import pandas as pd
production_fish = pd.read_csv( r"..\..\data\production_fish.csv" )

In [23]:
production_fish.head(3)

,year,Consumo Industrial - Anchoveta,Consumo Humano - Congelado - Concha de abanico,Consumo Humano - Congelado - Langostino,Consumo Humano - Congelado - Merluza,Consumo Humano - Congelado - Calamar gigante,Consumo Humano - Conservas - Atún,Consumo Humano - Conservas - Caballa,Consumo Humano - Conservas - Jurel,Consumo Humano - Conservas - Sardina,Consumo Humano - Fresco - Concha de abanico,Consumo Humano - Fresco - Jurel,Consumo Humano - Fresco - Liza,Consumo Humano - Fresco - Tollo,total_production
0,2005,8628.396,13.537,9.021,23.279000,235.630000,9.877000,25.711000,20.481000,0.16500,1.843080,56.167940,5.875600,0.430000,9030.413620
1,2006,5891.838,14.714,11.295,25.189000,365.729000,11.336000,58.245000,122.904000,0.04800,4.048000,136.827000,3.166000,1.584000,6646.923000
2,2007,6084.713,19.937,13.548,28.358488,379.556594,3.713293,26.248739,82.910307,0.00102,4.822991,134.887316,9.317622,2.834958,6790.849328

In [24]:
col_names = production_fish.columns.to_list()[ 1:-1 ]

In [25]:
for col in col_names:
    production_fish[ f'%_{col}' ]  = production_fish[ f'{col}' ] * 100 / production_fish[ 'total_production' ]

In [26]:
production_fish

,year,Consumo Industrial - Anchoveta,Consumo Humano - Congelado - Concha de abanico,Consumo Humano - Congelado - Langostino,Consumo Humano - Congelado - Merluza,Consumo Humano - Congelado - Calamar gigante,Consumo Humano - Conservas - Atún,Consumo Humano - Conservas - Caballa,Consumo Humano - Conservas - Jurel,Consumo Humano - Conservas - Sardina,...,%_Consumo Humano - Congelado - Merluza,%_Consumo Humano - Congelado - Calamar gigante,%_Consumo Humano - Conservas - Atún,%_Consumo Humano - Conservas - Caballa,%_Consumo Humano - Conservas - Jurel,%_Consumo Humano - Conservas - Sardina,%_Consumo Humano - Fresco - Concha de abanico,%_Consumo Humano - Fresco - Jurel,%_Consumo Humano - Fresco - Liza,%_Consumo Humano - Fresco - Tollo
0,2005,8628.396000,13.537000,9.021000,23.279000,235.630000,9.877000,25.711000,20.481000,0.165000,...,0.257784,2.609294,0.109375,0.284716,0.226800,0.001827,0.020410,0.621986,0.065065,0.004762
1,2006,5891.838000,14.714000,11.295000,25.189000,365.729000,11.336000,58.245000,122.904000,0.048000,...,0.378957,5.502230,0.170545,0.876270,1.849036,0.000722,0.060900,2.058501,0.047631,0.023831
2,2007,6084.713000,19.937000,13.548000,28.358488,379.556594,3.713293,26.248739,82.910307,0.001020,...,0.417599,5.589236,0.054681,0.386531,1.220912,0.000015,0.071022,1.986310,0.137208,0.041747
3,2008,6159.387000,18.790000,12.817000,26.348398,484.162082,3.283711,47.694121,58.864202,0.000000,...,0.381324,7.006976,0.047523,0.690247,0.851905,0.000000,0.011986,1.159134,0.210053,0.042453
4,2009,5828.636000,24.634372,11.877399,36.774763,355.106589,2.017061,51.355908,14.289041,0.000000,...,0.575057,5.552894,0.031541,0.803066,0.223441,0.000000,0.028821,0.736189,0.270702,0.063454
5,2010,3330.413040,60.001250,14.477939,25.647697,327.571909,9.182845,9.729522,5.774274,0.000000,...,0.673039,8.596043,0.240973,0.255319,0.151527,0.000000,0.074126,0.273043,0.254711,0.131070
6,2011,7000.092781,92.027637,23.384478,28.544458,373.195661,6.586856,20.478814,83.277943,0.054463,...,0.369781,4.834589,0.085330,0.265294,1.078830,0.000706,0.011311,0.945102,0.157072,0.073679
7,2012,3693.871080,38.933390,22.707220,21.054780,457.072670,1.115060,9.978510,43.693940,0.088460,...,0.480309,10.426908,0.025437,0.227633,0.996762,0.002018,0.016986,1.663716,0.391515,0.096619
8,2013,4754.118210,89.293284,19.111372,31.187461,410.759534,7.136436,26.600553,7.197624,0.000000,...,0.575572,7.580665,0.131705,0.490920,0.132834,0.000000,0.040237,1.004972,0.231259,0.072818
9,2014,2255.453460,52.266500,21.762990,30.770800,465.007580,4.734540,29.576440,8.882560,0.000000,...,1.049172,15.855062,0.161431,1.008449,0.302863,0.000000,0.020736,1.580245,0.417635,0.177536
10,2015,3616.481500,14.843150,26.772210,25.644130,426.932300,11.082120,15.314910,2.769796,0.164140,...,0.613740,10.217753,0.265228,0.366531,0.066289,0.003928,0.014741,0.419711,0.298289,0.184707
11,2016,2732.733740,10.090130,29.253750,25.800210,246.124700,10.884490,57.675170,0.412040,0.007490,...,0.818731,7.810397,0.345403,1.830235,0.013075,0.000238,0.018397,0.395782,0.500043,0.299981
12,2017,3165.490240,4.596090,38.760070,37.147430,252.429930,11.802750,23.249140,1.052910,0.000000,...,1.038349,7.055952,0.329912,0.649863,0.029431,0.000000,0.010446,0.192577,0.812337,0.187074
13,2018,6072.887839,36.530349,31.505879,34.876576,319.146488,18.138975,24.610468,14.619846,0.000000,...,0.528787,4.838788,0.275017,0.373135,0.221661,0.000000,0.023521,0.223194,0.353665,0.055675
14,2019,3381.437222,53.112863,42.857637,28.979849,483.765239,17.839298,19.598784,27.733432,0.000000,...,0.702947,11.734409,0.432717,0.475396,0.672714,0.000000,0.029751,0.989630,0.582877,0.030124
15,2020,4314.558220,46.995287,34.516971,19.842900,407.384850,3.843680,28.408700,23.475890,0.000000,...,0.401410,8.241159,0.077755,0.574691,0.474904,0.000000,0.012475,0.973355,0.303283,0.011017

In [6]:
col_names=production_fish.columns.to_list()[1:-1] #drop first and last column

col_names

NameError: name 'production_fish' is not defined

In [27]:
production_fish.loc[:, col_names ].round( 2 ) #redondear a 2 decimales

,Consumo Industrial - Anchoveta,Consumo Humano - Congelado - Concha de abanico,Consumo Humano - Congelado - Langostino,Consumo Humano - Congelado - Merluza,Consumo Humano - Congelado - Calamar gigante,Consumo Humano - Conservas - Atún,Consumo Humano - Conservas - Caballa,Consumo Humano - Conservas - Jurel,Consumo Humano - Conservas - Sardina,Consumo Humano - Fresco - Concha de abanico,Consumo Humano - Fresco - Jurel,Consumo Humano - Fresco - Liza,Consumo Humano - Fresco - Tollo
0,8628.40,13.54,9.02,23.28,235.63,9.88,25.71,20.48,0.16,1.84,56.17,5.88,0.43
1,5891.84,14.71,11.30,25.19,365.73,11.34,58.24,122.90,0.05,4.05,136.83,3.17,1.58
2,6084.71,19.94,13.55,28.36,379.56,3.71,26.25,82.91,0.00,4.82,134.89,9.32,2.83
3,6159.39,18.79,12.82,26.35,484.16,3.28,47.69,58.86,0.00,0.83,80.09,14.51,2.93
4,5828.64,24.63,11.88,36.77,355.11,2.02,51.36,14.29,0.00,1.84,47.08,17.31,4.06
5,3330.41,60.00,14.48,25.65,327.57,9.18,9.73,5.77,0.00,2.82,10.40,9.71,4.99
6,7000.09,92.03,23.38,28.54,373.20,6.59,20.48,83.28,0.05,0.87,72.96,12.12,5.69
7,3693.87,38.93,22.71,21.05,457.07,1.12,9.98,43.69,0.09,0.74,72.93,17.16,4.24
8,4754.12,89.29,19.11,31.19,410.76,7.14,26.60,7.20,0.00,2.18,54.45,12.53,3.95
9,2255.45,52.27,21.76,30.77,465.01,4.73,29.58,8.88,0.00,0.61,46.35,12.25,5.21
10,3616.48,14.84,26.77,25.64,426.93,11.08,15.31,2.77,0.16,0.62,17.54,12.46,7.72
11,2732.73,10.09,29.25,25.80,246.12,10.88,57.68,0.41,0.01,0.58,12.47,15.76,9.45
12,3165.49,4.60,38.76,37.15,252.43,11.80,23.25,1.05,0.00,0.37,6.89,29.06,6.69
13,6072.89,36.53,31.51,34.88,319.15,18.14,24.61,14.62,0.00,1.55,14.72,23.33,3.67
14,3381.44,53.11,42.86,28.98,483.77,17.84,19.60,27.73,0.00,1.23,40.80,24.03,1.24
15,4314.56,47.00,34.52,19.84,407.38,3.84,28.41,23.48,0.00,0.62,48.12,14.99,0.54

# 3.  Functions and classes 

### <a id = '#2.1'> 2.1 The Importance of Python Functions </a> 

- Abstraction and Reusability: Replicate the code you will use over and over again.
- Modularity: Functions allow complex processes to be broken up into smaller steps.
- Namespace Separation: It allows you to use variables  and used within a Python function even if they have the same name as variables defined in other functions or in the main program.

### <a ID = '#2.2'> 2.2 Function structure </a> 

A function requires **parameters**, **code** to execute and the **return** function. The **def** keyword introduces a new Python function definition.

This is the basic structure:
<br><br>

<font size="4">
def name_function<font color='green'>( parameter1, parameter2 )</font>: <br> <br>
&nbsp;&nbsp;&nbsp;&nbsp;Code<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>return</font> final_output<br>
</font>

In [28]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 90%; }
    div#menubar-container     { width: 90%; }
    div#maintoolbar-container { width: 99%; }a
</style>
"""))

In [29]:
# return squared result

def calculator(x,z,a):
    m = (x+z)**a
    
    return m

In [31]:
calculator(4,2,0.5)

2.449489742783178

### <a id='#'> !! Function without `return` function </a> 

This kind of function does not return any output

In [33]:
def calculator2(x,z,a):
    m = x+z+a

In [34]:
result = calculator2(10,5,8)

In [35]:
type(result)

NoneType

### <a id='2.2'> 2.2 Multiples outcomes </a>

In [36]:
# several kind of object 
# this function select elements of a list

def select(a):
    a1 = a[0]
    a2 = a[len(a)-1]
    
    return a1,a2,len(a)

In [37]:
lista = [2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]

output = select(lista)

f_element = output[0]
l_element = output[1]
num_element = output[2]

print('first element:',f_element,'\n','last_element:',l_element,'\n','number of elements:',num_element)

first element: 2011
 last_element: 2021
 number of elements: 11

In [38]:
#alternative to get outcome from function

output1,output2, output3 = select(lista)
print(output1)
print(output2)
print(output3)

2011
2021
11

### <a id='2.3'> 2.3 Conditional in function </a>

In [39]:
lista = [2000,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030]


def calculator_square( x, y ):
    
    results = x[y]
    
    if (1995 >= results):
        
         print( "Year is before 1995")
    
    elif ( 2005 >= results >= 1995):
        print( "Year is after 1995")
    
    elif (  2022 >= results > 2005 ):
        return results
    
    else:
        print( "Future Year !!")

In [40]:
calculator_square(lista,15)

Future Year !!

In [41]:
calculator_square(lista,0)

Year is after 1995

In [42]:
calculator_square(lista,1)

2010

# Error function

In [43]:
def calculator_base_5( x : int, y : float ) -> float:
    
    if not isinstance( x , int ):
        raise TypeError( "X variable is not int type.")
        
    if not isinstance( y, float ):
        raise TypeError( "Y variable is not float type.")

    result = x * y
    
    
    return result

In [44]:
calculator_base_5( 4.5, 3)

TypeError: X variable is not int type.

In [45]:
# From capital letters to lower

def lower_case( string1  ):
    
    str_result = string1.lower()
    
    return str_result

The `places_result` dictionary stores information from a Google API request that aims to geolocate all the National Identity Management Commission establishments in Nigeria. We want to store the results in a Pandas DataFrame. We want to keep the name of the establishment and its coordiantes.

# WORKING TO DICTIONARY FROM WEB'S INFORMATION

In [9]:
from tqdm import tqdm   #Pkg to measure time's loop
import pickle  #to load dictionary dataset
import pandas as pd #

In [7]:
dictionary_places = open( r"..\..\data\places_result", "rb")
places_result = pickle.load( dictionary_places )

In [17]:
places_result.keys()

dict_keys(['html_attributions', 'next_page_token', 'results', 'status'])

In [20]:
places_result['results']

[{'business_status': 'OPERATIONAL',
  'formatted_address': '11 Sokode Crescent, Off Dalaba Street Zone 5, Wuse P. M. B, 18, Garki, Abuja',
  'geometry': {'location': {'lat': 9.065977, 'lng': 7.4549606},
   'viewport': {'northeast': {'lat': 9.067332429892723,
     'lng': 7.456282779892721},
    'southwest': {'lat': 9.064632770107277, 'lng': 7.453583120107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1080,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110095172826797559117">Fortune Arinze</a>'],
    'photo_reference': 'ATtYBwIfz2h2rM_FJkG-yQBlkVWKeovt6ifUcEMS-oibn4T5zgXhLpqhrl1lj07-RfAhWjrwClBoAgc_3Ckh-TekOWbaaQu-0J03OHYQBMqZK6xYSOonfP3tABNHcj_--1XB6urnlYHXNenRO8RhLJC9ahW3AjPS3t2Z4Ssh9hV-hQ-VjJuy',
    'width': 1920}],
  'place_id': 'ChIJwRTVOSELThARczd6MyuWUbs',
  'plus_code': {'compound_code': '3F83+9X Abuja',
   'global_code': '6FX93F83+9X'},
  'rating': 3.8,
  'reference': 'ChIJwRTVOSELThARczd6MyuWUbs',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 314},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Lafia - Shandam Rd, Lafia',
  'geometry': {'location': {'lat': 8.50573, 'lng': 8.531774799999999},
   'viewport': {'northeast': {'lat': 8.506788579892724,
     'lng': 8.53327222989272},
    'southwest': {'lat': 8.50408892010728, 'lng': 8.530572570107276}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission NIMC',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1836,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104393542635093633733">Masoyi Sanda</a>'],
    'photo_reference': 'ATtYBwIE0LfhdRfp-T7JDNqlTgrqdBl2ZWIi0oin4Qv1qcHhrTgfSxBEAaJ29-WNNItxySXH14L1i78PN506HBFHbRrOU_vxYye70ll_1fwxWDqaqja6p4IZ6h-SLnoAEPI1eNayQcyoDoDrB438layysV-a7oIQuNJv9j3Hsv0nkWgDGo4',
    'width': 3264}],
  'place_id': 'ChIJt-5bYuEGURARJyb82LfQ97A',
  'plus_code': {'compound_code': 'GG4J+7P Lafia',
   'global_code': '6FWCGG4J+7P'},
  'rating': 3.7,
  'reference': 'ChIJt-5bYuEGURARJyb82LfQ97A',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 3},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Asa-Dam Rd, opp. Dangote Flour Mills, Ilorin',
  'geometry': {'location': {'lat': 8.450151, 'lng': 4.542503},
   'viewport': {'northeast': {'lat': 8.451072679892722,
     'lng': 4.543705329892721},
    'southwest': {'lat': 8.448373020107278, 'lng': 4.541005670107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJEZsSsTetNxAR1dg3wSeUrCA',
  'plus_code': {'compound_code': 'FG2V+32 Ilorin',
   'global_code': '6FW6FG2V+32'},
  'rating': 4,
  'reference': 'ChIJEZsSsTetNxAR1dg3wSeUrCA',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 24},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'zone 3, No 4 Maputo St, Wuse, Abuja',
  'geometry': {'location': {'lat': 9.058854499999999,
    'lng': 7.468077600000001},
   'viewport': {'northeast': {'lat': 9.06035997989272,
     'lng': 7.469236379892722},
    'southwest': {'lat': 9.057660320107276, 'lng': 7.466536720107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 2448,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/100674673329877445887">Jacks Elsa</a>'],
    'photo_reference': 'ATtYBwIWfQb45CnKaFUronntBzevJLHPQ6VMm1xhH6_ixbu8Ilkhe1Eo3im_h0_KN3h89dYJ1arCflM3RwFxGg0fcnsy8BsVDxCQ7rfkTCoh9Q0PX-et_eNpyT6WnjmVK0O6VPA33Vk7ZPFjE7kqcE6G-gHV4AhzaTgt9csg6xZC60il5kL6',
    'width': 3264}],
  'place_id': 'ChIJbZxZhq4LThARg41HgXp5W2w',
  'plus_code': {'compound_code': '3F59+G6 Abuja',
   'global_code': '6FX93F59+G6'},
  'rating': 3.4,
  'reference': 'ChIJbZxZhq4LThARg41HgXp5W2w',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 23},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Lamingo Dam Road Plateau',
  'geometry': {'location': {'lat': 9.895973, 'lng': 8.931434},
   'viewport': {'northeast': {'lat': 9.8984195, 'lng': 8.9328039},
    'southwest': {'lat': 9.895157499999998, 'lng': 8.927324300000002}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJUxzO3-lxUxARdZDox6KE6UQ',
  'plus_code': {'compound_code': 'VWWJ+9H Jos', 'global_code': '6FXCVWWJ+9H'},
  'rating': 0,
  'reference': 'ChIJUxzO3-lxUxARdZDox6KE6UQ',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 0},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Jos',
  'geometry': {'location': {'lat': 9.892294699999999, 'lng': 8.9175658},
   'viewport': {'northeast': {'lat': 9.893702729892722,
     'lng': 8.91888807989272},
    'southwest': {'lat': 9.891003070107278, 'lng': 8.916188420107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1080,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116242405272440066619">Aliyu zainul abideen</a>'],
    'photo_reference': 'ATtYBwJG5OL_3UP7QDjcMop8AYOD_0fN64mXYffPH5XdLCMLFBFSo0vBZpBBOZZ8LQvxLeSK86QQ-dge4oPX7EDL32eX0G-y_P1lV9BcedkKnhPKn379kdAFIQsiuKhJ56iWGfTT6prFd5DinmvO26zgmj11TuTeEWNs6X_Bf0wp7thjHFG5',
    'width': 1920}],
  'place_id': 'ChIJFWiUH-dzUxAR55hi-MYXLwg',
  'plus_code': {'compound_code': 'VWR9+W2 Jos', 'global_code': '6FXCVWR9+W2'},
  'rating': 3.3,
  'reference': 'ChIJFWiUH-dzUxAR55hi-MYXLwg',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 7},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Kachia',
  'geometry': {'location': {'lat': 9.8572331, 'lng': 7.967971899999998},
   'viewport': {'northeast': {'lat': 9.858620379892722,
     'lng': 7.969346929892722},
    'southwest': {'lat': 9.855920720107278, 'lng': 7.966647270107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission',
  'place_id': 'ChIJ80U4ZjyJUhARGk5bZlIeNzY',
  'plus_code': {'compound_code': 'VX49+V5 Kachia',
   'global_code': '6FX9VX49+V5'},
  'rating': 0,
  'reference': 'ChIJ80U4ZjyJUhARGk5bZlIeNzY',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 0},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Jonah Jang Cres, High Level, Makurdi',
  'geometry': {'location': {'lat': 7.711655800000001, 'lng': 8.5265235},
   'viewport': {'northeast': {'lat': 7.712382379892722,
     'lng': 8.528209429892721},
    'southwest': {'lat': 7.709682720107278, 'lng': 8.525509770107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1080,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104445494535423861947">Slim Meyo</a>'],
    'photo_reference': 'ATtYBwK9R9it21i9oYROE6AEzcPpr2Uh2SidNYIJ0ABxd2uvA23NORVr0_xmD8jqtkCoCYLCu8htDa0foSkd6gLhnJPOE0BERWmHDzAne-ZqFrPU0kEBIiH1SJe-6hORIFZ2IEJBDumAac7twjhaxLOZD-9ApAlaFzruj_oz6K4Yl1ayJ4CG',
    'width': 1920}],
  'place_id': 'ChIJ51B2sMGBUBARDKibZrme9gU',
  'plus_code': {'compound_code': 'PG6G+MJ Makurdi',
   'global_code': '6FVCPG6G+MJ'},
  'rating': 3.1,
  'reference': 'ChIJ51B2sMGBUBARDKibZrme9gU',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 35},
 {'business_status': 'OPERATIONAL',
  'formatted_address': '3 Abdulkadir ahmed Close (P.M.B 0281, Bauchi',
  'geometry': {'location': {'lat': 10.310332, 'lng': 9.826602},
   'viewport': {'northeast': {'lat': 10.31170367989272,
     'lng': 9.827927879892721},
    'southwest': {'lat': 10.30900402010728, 'lng': 9.825228220107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1920,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102114576626040120313">Mohammed Zahradeen Umar</a>'],
    'photo_reference': 'ATtYBwL3WNqJiitCLNWeKUU4uye8FUfn0vUNZ_UyCuS0IIY4JojJnFhaGxaxpgSh7CWnoTEAzbmk81iynWT0_lruLYtAzZ3Bx0Yvjf3yLHlt0lI3dsuD5BRY7zWy2luqKxKW9J14Plb_-6GPdiUw1AHmCCMBfvZAshlpha8mlvB6QLW012FR',
    'width': 1088}],
  'place_id': 'ChIJ4X2l_AXXVBAR7v-eH-d9h3E',
  'plus_code': {'compound_code': '8R6G+4J Bauchi',
   'global_code': '7F2F8R6G+4J'},
  'rating': 0,
  'reference': 'ChIJ4X2l_AXXVBAR7v-eH-d9h3E',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 0},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Kofar Kabuga, Kano',
  'geometry': {'location': {'lat': 11.9899944, 'lng': 8.4891647},
   'viewport': {'northeast': {'lat': 11.99139672989272,
     'lng': 8.490334129892721},
    'southwest': {'lat': 11.98869707010728, 'lng': 8.487634470107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJE0nEt4CArhERRs1UvLzYZjY',
  'plus_code': {'compound_code': 'XFQQ+XM Kano', 'global_code': '7F3CXFQQ+XM'},
  'rating': 4.4,
  'reference': 'ChIJE0nEt4CArhERRs1UvLzYZjY',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 12},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Complex, Federal Secretariat, Kawo, Kaduna',
  'geometry': {'location': {'lat': 10.592473, 'lng': 7.449456},
   'viewport': {'northeast': {'lat': 10.59382137989272,
     'lng': 7.450810429892722},
    'southwest': {'lat': 10.59112172010728, 'lng': 7.448110770107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJyZiAR9q1shERK9gFL9AG44I',
  'plus_code': {'compound_code': 'HCRX+XQ Kaduna',
   'global_code': '7F29HCRX+XQ'},
  'rating': 0,
  'reference': 'ChIJyZiAR9q1shERK9gFL9AG44I',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 0},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Port-Hacourt Rd, New Owerri, Owerri',
  'geometry': {'location': {'lat': 5.4717813, 'lng': 7.0083439},
   'viewport': {'northeast': {'lat': 5.473014629892722,
     'lng': 7.009477279892723},
    'southwest': {'lat': 5.470314970107278, 'lng': 7.006777620107279}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Center',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJ8-OsvX1ZQhARaNsdHakfc98',
  'plus_code': {'compound_code': 'F2C5+P8 Owerri',
   'global_code': '6FQ9F2C5+P8'},
  'rating': 2.8,
  'reference': 'ChIJ8-OsvX1ZQhARaNsdHakfc98',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 13},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'ITF House, 6, 3rd Floor, Adetokunbo Ademola Cres, Wuse 2, Abuja',
  'geometry': {'location': {'lat': 9.07677, 'lng': 7.493777},
   'viewport': {'northeast': {'lat': 9.078071879892722,
     'lng': 7.495215229892723},
    'southwest': {'lat': 9.075372220107278, 'lng': 7.492515570107279}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJu0OOSjELThAR4d7V7h1GgD4',
  'plus_code': {'compound_code': '3FGV+PG Abuja',
   'global_code': '6FX93FGV+PG'},
  'rating': 3,
  'reference': 'ChIJu0OOSjELThAR4d7V7h1GgD4',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 1},
 {'business_status': 'OPERATIONAL',
  'formatted_address': '9 Obafemi Awolowo Way, Agidingbi, Ikeja',
  'geometry': {'location': {'lat': 6.617086, 'lng': 3.357951},
   'viewport': {'northeast': {'lat': 6.618298179892721,
     'lng': 3.359587779892722},
    'southwest': {'lat': 6.615598520107278, 'lng': 3.356888120107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commision (NIMC) Lagos',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 2836,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109021919043392669000">Austin Chikwado Ofor</a>'],
    'photo_reference': 'ATtYBwK-FH7TBnp06XKVDdyzuJrjhWpUAFlugsW1s7ZJKGblziN5YFl8tQWsTFYaHm8rv3k3W701YYMM05LadTLUQ_nbBoK4eGYjYr0da8OYISM4Ra7bPKfttsbdkq6E5q4zpKB-WaW-JciS3-uewEXc4dsw2qojP0hbHuUnCECygykmgSsF',
    'width': 2358}],
  'place_id': 'ChIJD34txsmTOxAR5AEgvWczmGI',
  'plus_code': {'compound_code': 'J985+R5 Ikeja',
   'global_code': '6FR5J985+R5'},
  'rating': 3.4,
  'reference': 'ChIJD34txsmTOxAR5AEgvWczmGI',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 53},
 {'business_status': 'OPERATIONAL',
  'formatted_address': '1 Proda Road,Proda Junction, Emene industrial Layout',
  'geometry': {'location': {'lat': 6.460105899999999,
    'lng': 7.579008999999999},
   'viewport': {'northeast': {'lat': 6.461432879892723,
     'lng': 7.580321279892722},
    'southwest': {'lat': 6.458733220107279, 'lng': 7.577621620107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 2048,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116030890989805302110">onyi okeke</a>'],
    'photo_reference': 'ATtYBwJmt3EyNK4J1abWzGe-QT8jIL4LxmPvkFSZ-swph7NeBR4dY2KGdamn-ru4FFYoxTOYgIm8lhvTkaoGBXfQIgbKYTPCkm0FKwRfPB_xJpiWvHk5jeFtnO5RM3lZ_Lpe9xVNVaMm08DtlCkeM7Ils8WFGri7_BKNtg0vqd0T_vCdJ9I3',
    'width': 1152}],
  'place_id': 'ChIJ87i9KbilRBARjzOeBDbKx-c',
  'plus_code': {'compound_code': 'FH6H+2J Enugu',
   'global_code': '6FR9FH6H+2J'},
  'rating': 4,
  'reference': 'ChIJ87i9KbilRBARjzOeBDbKx-c',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 26},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Bayajida Rd, Ungwan Munchi, Kaduna',
  'geometry': {'location': {'lat': 10.5436173, 'lng': 7.4609879},
   'viewport': {'northeast': {'lat': 10.54495552989272,
     'lng': 7.46233667989272},
    'southwest': {'lat': 10.54225587010728, 'lng': 7.459637020107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission, Northwest Zonal Office',
  'place_id': 'ChIJS98oGDi1shER1iS7xWsBExw',
  'plus_code': {'compound_code': 'GFV6+C9 Kaduna',
   'global_code': '7F29GFV6+C9'},
  'rating': 2,
  'reference': 'ChIJS98oGDi1shER1iS7xWsBExw',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 1},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Tal-Udu, FCE Junction Kano',
  'geometry': {'location': {'lat': 11.988203, 'lng': 8.496804},
   'viewport': {'northeast': {'lat': 11.98937482989272,
     'lng': 8.498143229892724},
    'southwest': {'lat': 11.98667517010728, 'lng': 8.49544357010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission (Nimc)',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJRbzDx9CBrhERDCs5gEROpvQ',
  'plus_code': {'compound_code': 'XFQW+7P Kano', 'global_code': '7F3CXFQW+7P'},
  'rating': 5,
  'reference': 'ChIJRbzDx9CBrhERDCs5gEROpvQ',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 1},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Ndume bypass, Ndume',
  'geometry': {'location': {'lat': 5.5025021, 'lng': 7.517955600000001},
   'viewport': {'northeast': {'lat': 5.503745479892721,
     'lng': 7.519157379892723},
    'southwest': {'lat': 5.501045820107277, 'lng': 7.51645772010728}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission Umuahia',
  'opening_hours': {'open_now': False},
  'place_id': 'ChIJyTS2v4zDQhARJtViYuKIT54',
  'plus_code': {'compound_code': 'GG39+25 Ndume',
   'global_code': '6FQ9GG39+25'},
  'rating': 3.7,
  'reference': 'ChIJyTS2v4zDQhARJtViYuKIT54',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 3},
 {'business_status': 'OPERATIONAL',
  'formatted_address': 'Umueme, Port Harcourt',
  'geometry': {'location': {'lat': 4.822006, 'lng': 7.0079724},
   'viewport': {'northeast': {'lat': 4.823459929892723,
     'lng': 7.009288279892722},
    'southwest': {'lat': 4.820760270107279, 'lng': 7.006588620107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission',
  'photos': [{'height': 4608,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/105954586937635012132">Eleje Chinwendu</a>'],
    'photo_reference': 'ATtYBwJPiTOSvWYumHd9rsNgskLV3VcdNpzOvHKXjRAPQoNinDDB_-3j-8utI5ABTIGc0RA_FboBx_inOA6XhCqzsjcBRnV2rjW-DcfeHXVFEYFUNHoq4EJgkRlSi3CfZFZlOwSkrCjvUtAMSDfl6ZSvOr_Ore3Z4F-n2I2sgsnDKwNEyb3I',
    'width': 2240}],
  'place_id': 'ChIJ79K8E9bNaRARd51XXSlz0Kc',
  'plus_code': {'compound_code': 'R2C5+R5 Port Harcourt',
   'global_code': '6FP9R2C5+R5'},
  'rating': 3.6,
  'reference': 'ChIJ79K8E9bNaRARd51XXSlz0Kc',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 12},
 {'business_status': 'OPERATIONAL',
  'formatted_address': '238 Port Harcourt - Aba Expy, Rumuokwurusi, Port Harcourt',
  'geometry': {'location': {'lat': 4.8496083, 'lng': 7.0527365},
   'viewport': {'northeast': {'lat': 4.850934679892722,
     'lng': 7.054089179892721},
    'southwest': {'lat': 4.848235020107278, 'lng': 7.051389520107278}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/civic_building-71.png',
  'name': 'National Identity Management Commission Nimc',
  'place_id': 'ChIJgRk7A3nNaRAR61Ty7IIGSkU',
  'plus_code': {'compound_code': 'R3X3+R3 Port Harcourt',
   'global_code': '6FP9R3X3+R3'},
  'rating': 3,
  'reference': 'ChIJgRk7A3nNaRAR61Ty7IIGSkU',
  'types': ['point_of_interest', 'establishment'],
  'user_ratings_total': 4}]

In [10]:
# Lists
latitudes = []
longitudes = []
institutions = []


# define all the results
results = places_result[ 'results' ]
# loop para guardar cada uno de los elementos
for row in tqdm( range( 0 , len( results ) ) ):
    
    # latitude
    lat = results[ row ]['geometry']['location']['lat']
    
    # Longitude
    lng = results[ row ]['geometry']['location']['lng']
    
    # nombre de la institution
    institution = results[ row ]['name']
    
    # Save results
    latitudes.append( lat )
    longitudes.append( lng )
    institutions.append( institution )
    
# Diccionario
final_result = { 'Institution': institutions, 'Latitud' : latitudes, 'Longitud' : longitudes }
# Dataframe
df_result = pd.DataFrame( final_result )
df_result

100%|███████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 10024.63it/s]

                                          Institution    Latitud  Longitud
0             National Identity Management Commission   9.065977  7.454961
1        National Identity Management Commission NIMC   8.505730  8.531775
2      National Identity Management Commission (Nimc)   8.450151  4.542503
3             National Identity Management Commission   9.058854  7.468078
4      National Identity Management Commission (Nimc)   9.895973  8.931434
5             National Identity Management Commission   9.892295  8.917566
6             National Identity Management Commission   9.857233  7.967972
7      National Identity Management Commission (Nimc)   7.711656  8.526523
8      National Identity Management Commission (Nimc)  10.310332  9.826602
9             National Identity Management Commission  11.989994  8.489165
10     National Identity Management Commission (Nimc)  10.592473  7.449456
11                National Identity Management Center   5.471781  7.008344
12     National Identity Management Commission (Nimc)   9.076770  7.493777
13  National Identity Management Commision (NIMC) ...   6.617086  3.357951
14            National Identity Management Commission   6.460106  7.579009
15  National Identity Management Commission, North...  10.543617  7.460988
16     National Identity Management Commission (Nimc)  11.988203  8.496804
17    National Identity Management Commission Umuahia   5.502502  7.517956
18            National Identity Management Commission   4.822006  7.007972
19       National Identity Management Commission Nimc   4.849608  7.052736